project/account/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    path('status/get/<owner>/', 
         views.PublicStatusRetrieveView.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

project/account/urls.py
from django.urls import path,include
from django.contrib.auth import views as av
from .views import *

urlpatterns = [
    #auth reg
    path('register/',register,name='register'),
    path('edit/',edit,name='edit'),
    path('', include('django.contrib.auth.urls')),
    #main
    path('api/profile/',include('account.api.urls',)),

    path('profile/<int:pk>/',profile_detail,name='profile_detail'),
    path('',dashboard,name='dashboard'),
]

project/chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'

urlpatterns = [
    path('',views.get_chats ,name='all_chats'),
]

project/friendship/urls.py
from django.urls import path
from . import views

app_name = 'friendship'

urlpatterns = [
    path('',views.all_people ,name='people'),
]

project/account/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


def get_avatar_place(instance, filename):
    return f'users/{instance.user}/avatar/{filename}'


class Profile(models.Model):
    """
    This model will be created every time when user registration pass.
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                related_name='profile')

    friends = models.ManyToManyField(
        'self',
        through='friendship.Friends',
        blank=True,
        null=True,
    )

    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to=get_avatar_place, blank=True)
    city = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("profile_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        self.pk = self.user.pk
        super().save(*args, **kwargs)


class PublicStatus(models.Model):
    owner = models.OneToOneField(Profile, on_delete=models.CASCADE)
    status_text = models.CharField(max_length=250, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.owner.user} status created at: {self.created}"

project/account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from .services import get_years_range



class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','first_name','last_name','email',)


    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match')
        return cd['password2']



class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

#________________________________________________

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email',)


class ProfileEditForm(forms.ModelForm):
    date_of_birth =  forms.DateField(widget=forms.SelectDateWidget(years=get_years_range()))
    photo =forms.ImageField(widget=forms.FileInput(attrs={'class':'chooseFileButton','row':1,}))
    class Meta:
        model = Profile
        fields = ('date_of_birth','photo')

project/account/api/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from .serializers import *
from account.models import Profile,PublicStatus


class PublicStatusRetrieveView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = PublicStatusSerializer
    queryset = PublicStatus.objects.all()
    lookup_field = 'owner'
    permission_classes = [IsAuthenticated,]

project/account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Profile, PublicStatus
from .forms import *
from django.contrib import messages
from django.views.decorators.http import require_http_methods
from posts.models import Post
from .services import check_friendship, check_friendship_request, \
    check_accepted_fr_req


# in developing|security faulth
@require_http_methods(["GET"])
@login_required
def profile_detail(request, pk):
    profile = get_object_or_404(Profile, user=pk)
    public_status = PublicStatus.objects.get(owner=profile)
    posts = Post.objects.filter(active=True, profile=profile).order_by(
        '-created')

    my_friend_or_not = check_friendship(request.user.profile, profile)
    friendship_request = check_friendship_request(request.user.profile,
                                                  profile)
    accepted_fr_req = check_accepted_fr_req(request.user.profile, profile)

    return render(request, 'account/profile_detail.html', {
        'section': 'People',
        'profile': profile,
        'public_status': public_status,
        'posts': posts,
        'my_friend_or_not': my_friend_or_not,
        'friend_request': friendship_request,
        'accepted_fr_req': accepted_fr_req,
    })


@login_required
def dashboard(request):
    profile = get_object_or_404(Profile, user=request.user)
    public_status = PublicStatus.objects.get(owner=profile)
    posts = Post.objects.filter(active=True, profile=profile).order_by(
        '-created')

    return render(request, 'account/dashboard.html', {
        'section': 'Profile',
        'profile': profile,
        'public_status': public_status,
        'posts': posts,
    })


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            # Create new profile with new user
            profile = Profile.objects.create(user=new_user)
            PublicStatus.objects.create(owner=profile)
            return render(request, 'account/register_done.html',
                          {'new_user': new_user, })
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form, })


@login_required
def edit(request):
    """Profile edit"""
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            messages.success(request, 'Profile updated successfully')
            user_form.save()
            profile_form.save()
            return redirect('dashboard')

        else:
            messages.error(request, 'Error updating your profile')

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request, 'account/edit.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })

project/account/templates/base.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static 'icon/DevBook.png' %}" />
    <!-- Bootstrap CSS / Fonts -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- End -->
    <title>Devbook</title>
  </head>
<body>
    <!-- Navbar  -->
    <header class="p-2 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="fw-bold d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <span>Dev<span class="booktext">book</span></span>
        </a>
        <ul class="my-cs nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'dashboard' %}" class="nav-link px-2 {%if section == "Profile"%}text-secondary{%else%} text-white{%endif%}">Profile</a></li>
            <li><a href="#" class="nav-link px-2 {%if section == "Timeline"%}text-secondary{%else%} text-white{%endif%}">Timeline</a></li>
            <li><a href="{% url 'chats:all_chats' %}" class="nav-link px-2 {%if section == "Messages"%}text-secondary{%else%} text-white{%endif%}">Messages</a></li>
            <li><a href="{% url 'friendship:people' %}" class="nav-link px-2 {%if section == "People"%}text-secondary{%else%} text-white{%endif%}">People</a></li>
        </ul>       
        {%endif%}
        <div class="text-end">
            {% if request.user.is_authenticated %}
                Hello {{ request.user }}
                <a href="{% url 'logout' %}">| <span class='logout'>Logout</span></a>
            {% else %}
            <a href="{% url 'login' %}"><button type="button" id="loginPage" class="btn btn-outline-light me-2">Login</button></a>
            <a href="{% url 'register' %}"><button type="button" id="signPage" class="btn btn-warning">Sign-up</button></a>
            {%endif%}
        </div>
        </div>
        
    </div>
    </header>
    <!-- end Navbar -->
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li class="{{ message.tags }}">
    {{ message|safe }}
    </li>
    {% endfor %}
    </ul>
    {% endif %}
    <div class="main-container container">
        {% block content %}
        {% endblock content %}
    </div>


    <!-- footer -->
    <!-- endfooter -->
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>    
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script type="text/javascript" src="{%static 'js/main.js'%}"></script>
    <script type="text/javascript">{%block js%}{%endblock js%}</script>
</body>
</html>